spring.application.name=gestion-clinica
spring.jpa.properties.hibernate.format_sql=true

# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_clinica?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=gorrio2006.


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

